### ISSUE TITLE
Have you finished the oriented 3D bounding box output？

### ISSUE THREAD

**Issue by deepmeng** [AI-liu/Complex-YOLO#11]
The Complex-YOLO paper shows oriented bounding boxes in bird view images and the authors injects a predefined height for every object. Do you finish the orientation regression and injecting the predefined height?

**Comment by ghimiredhikura** [comment]
hi @deepmeng, 

Check this one: [https://github.com/ghimiredhikura/Complex-YOLO-V3](https://github.com/ghimiredhikura/Complex-YOLO-V3)

**Comment by deepmeng** [comment]
@ghimiredhikura Many thanks!
