### ISSUE TITLE
How can I draw rotated box in bev image? 

### ISSUE THREAD

**Issue by ghimiredhikura** [AI-liu/Complex-YOLO#17]
Thanks.

**Comment by abhigoku10** [comment]
@ghimiredhikura  are you able to draw the rotated box on the bev image if so can suggest the ways to do it

**Comment by ghimiredhikura** [comment]
check this fork, which includes rotated box drawing scripts. 
https://github.com/ghimiredhikura/Complex-YOLO

**Comment by abhigoku10** [comment]
@ghimiredhikura  thanks for the quick response , i have one more query . once u train the model do u get wrong class predictions
